import "./globals.css";
import PreloaderProvider from "./PreloaderProvider";
import { Web3Modal } from "@/context/Web3Modal";

export const metadata = {
  title: "Force Finance Coin | DEX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Web3Modal>
          <PreloaderProvider>{children}</PreloaderProvider>
        </Web3Modal>
      </body>
    </html>
  );
}
