import Header from "@/components/headers/Header";
import "./globals.css";
import PreloaderProvider from "./PreloaderProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PreloaderProvider>{children}</PreloaderProvider>
      </body>
    </html>
  );
}
