import Header from "@/components/Header";
import { archivo } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
